name: 🐞 Bug
description: Signaler un bug
labels: [bug]
body:
  - type: input
    id: nom
    attributes:
      label: Qui êtes-vous ?
      placeholder: Prénom
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Que s'est-il passé ?
      placeholder: Décris le bug
    validations:
      required: true
